# Generated by Django 4.2.2 on 2023-07-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0006_alter_post_image_or_video_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
