# Generated by Django 4.2.2 on 2023-07-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_alter_like_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_or_video_content',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='post_content'),
        ),
    ]
