# Generated by Django 4.2.2 on 2023-07-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='user_like',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
