# Generated by Django 4.2.2 on 2023-07-06 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0010_rename_user_like_user_like_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user_like', 'post')},
        ),
    ]
