# Generated by Django 4.2.2 on 2023-07-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0011_alter_like_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
